### ISSUE TITLE
error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by devfacet** [couchbase/goforestdb#17]
Any thoughts on following error?  ( I'm using `go1.5.1 darwin/amd64` on `OSX 10.10.5` ( Yosemite ) with latest ForestDB )

``` go
package main

import (
    "fmt"

    "github.com/couchbase/goforestdb"
)

func main() {
    fmt.Println("test")

    // Open a database
    db, _ := forestdb.Open("test", nil)

    // Close it properly when we're done
    defer db.Close()
}
```

```
$ go run main.go 
test
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x414c320, 0x2a)
  /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
  /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4001d40, 0xc82004dc70, 0xc800000000)
  /usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc82004dc50 sp=0xc82004dc20
github.com/couchbase/goforestdb._Cfunc_fdb_get_default_config(0x100004000008, 0x8000000, 0x1000, 0x1, 0x105400001, 0x1e00000104000000, 0x100000, 0xf, 0xc82001c001, 0x1e, ...)
  ??:0 +0x45 fp=0xc82004dc70 sp=0xc82004dc50
github.com/couchbase/goforestdb.DefaultConfig(0xc820062270)
  gocode/src/github.com/couchbase/goforestdb/config.go:201 +0x82 fp=0xc82004de30 sp=0xc82004dc70
github.com/couchbase/goforestdb.Open(0x4123050, 0x4, 0x0, 0x0, 0x0, 0x0)
  gocode/src/github.com/couchbase/goforestdb/file.go:30 +0x51 fp=0xc82004ded0 sp=0xc82004de30
main.main()
  main.go:13 +0xf2 fp=0xc82004df50 sp=0xc82004ded0
runtime.main()
  /usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc82004dfa0 sp=0xc82004df50
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82004dfa8 sp=0xc82004dfa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
exit status 2
```

`goforestdb` tests are okay;

```
go test -v .
=== RUN   TestSnapshotAndRollback
--- PASS: TestSnapshotAndRollback (0.00s)
=== RUN   TestForestDBCrud
--- PASS: TestForestDBCrud (0.00s)
=== RUN   TestForestDBCompact
--- PASS: TestForestDBCompact (0.02s)
=== RUN   TestForestDBCompactUpto
--- PASS: TestForestDBCompactUpto (0.00s)
=== RUN   TestForestDBConcurrent
--- PASS: TestForestDBConcurrent (4.59s)
=== RUN   TestForestDBIterator
--- PASS: TestForestDBIterator (0.00s)
=== RUN   TestForestDBIteratorSeq
--- PASS: TestForestDBIteratorSeq (0.00s)
=== RUN   TestForestDBIteratorSeek
--- PASS: TestForestDBIteratorSeek (0.00s)
=== RUN   TestForestDBIteratorPrev
--- PASS: TestForestDBIteratorPrev (0.00s)
=== RUN   TestForestDBIteratorOnSnapshot
--- PASS: TestForestDBIteratorOnSnapshot (0.00s)
=== RUN   TestForestDBIteratorPreAlloc
--- PASS: TestForestDBIteratorPreAlloc (0.00s)
=== RUN   TestForestDBIteratorBug
--- PASS: TestForestDBIteratorBug (0.00s)
=== RUN   TestForestDBKVCrud
--- PASS: TestForestDBKVCrud (0.00s)
=== RUN   TestForestDBKVBatch
--- PASS: TestForestDBKVBatch (0.00s)
=== RUN   TestPool
--- PASS: TestPool (0.00s)
=== RUN   TestSnapshotMarkersSingleKvs
--- PASS: TestSnapshotMarkersSingleKvs (0.00s)
=== RUN   TestSnapshotMarkersMultiKvs
--- PASS: TestSnapshotMarkersMultiKvs (0.00s)
=== RUN   TestTx
--- PASS: TestTx (0.00s)
PASS
ok      github.com/couchbase/goforestdb 4.638s
```

**Comment by cmfatih** [comment]
Looks like it was a local issue. I solved it by rebuilding ForestDB
